version: '2'
 
volumes:
    db-data:
    www-data:
 
services:
    mysql:
        container_name: mysql
        image: mysql:5
        ports:
            - "3308:3306"
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: prestashop
        restart: always
    apache:
        container_name: web
        build: ./prestashop
        environment:
            PS_INSTALL_AUTO: 1
            PS_DEV_MODE: 1
            DB_PASSWD: password
            DB_NAME: prestashop
            DB_SERVER: mysql
            PS_DOMAIN: localhost:8001
            PS_FOLDER_INSTALL: install-dev
            PS_FOLDER_ADMIN: admin-dev
        ports:
            - "8001:80"
        volumes:
            - www-data/:/var/www/html/
            - ./../../:/var/www/html/modules/boekuwzending
        restart: always