name: Build, package and release zip-file
on:
  release:
    types: [published]
jobs:
  build-and-zip:
    name: Build, package and release zip-file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        env:
          COMPOSER_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: composer install --no-dev --optimize-autoloader

      - name: Copy into "temp-to-zip/boekuwzending/" directory
        run: |
          mkdir -p temp-to-zip/boekuwzending/
          ls -A | grep -v "temp-to-zip" | xargs cp -r -t temp-to-zip/boekuwzending/

      - name: Copy the template "index.php" to all subdirectories
        run: find "temp-to-zip/boekuwzending/" -type d -exec cp "dist/index.php" {} \;

      - name: Zip "temp-to-zip/boekuwzending" release
        uses: thedoctor0/zip-release@master
        with:
          directory: temp-to-zip
          filename: 'boekuwzending.zip'
          exclusions: '*.git* *.idea* /*dist/* /*docker/* *config.xml'

      - name: Upload PrestaShop zipped module
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: temp-to-zip/boekuwzending.zip
          asset_name: boekuwzending.zip
          asset_content_type: application/zip